repos:
  - repo: local
    hooks:
      # https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [pre-commit]
        language: system
        entry: uv run jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
      - id: ruff_format
        name: ruff_format 
        entry: uv tool run ruff format
        language: system
        types: [python]
        files: "^popsim/"
        exclude: "^popsim/tests/"
      - id: ruff_check
        name: ruff_check
        entry: uv tool run ruff check --fix
        language: system
        types: [python]
        files: "^popsim/"
        exclude: "^popsim/tests/"
      - id: isort
        name: isort
        entry: uv tool run ruff check --select I001 --fix
        language: system
        types: [python]
