version: 2

submodules:
  include: all
  recursive: true

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  jobs:
    post_install:
      # Install uv
      - $READTHEDOCS_VIRTUALENV_PATH/bin/pip install uv
      # We got a lot of distlib missing errors in doc building, so explicitly install it.
      - $READTHEDOCS_VIRTUALENV_PATH/bin/pip install distlib
      # Install dependencies with 'dev' dependency group
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --group dev

mkdocs:
  configuration: mkdocs.yml