# Based, in part, on the equinox mkdocs.yml file:
# https://github.com/patrick-kidger/equinox/blob/main/mkdocs.yml
theme:
    name: material
    features:
        - navigation.sections
        - toc.integrate
        - header.autohide
    palette:
        - scheme: default
          primary: deep orange
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: deep purple
          accent: indigo
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/sun-compass"

site_name: "POPSIM: Plasma OPerational SIMulation"
site_description: The documentation for POPSIM.
site_author: The POPSIM Team.
edit_uri: ""

repo_url: https://github.com/cfs-energy-internal/POPSIM
repo_name: cfs-energy-internal/POPSIM

strict: false

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allow hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - pymdownx.tasklist:
        custom_checkbox: true
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

extra_javascript:
    # Make mathjax work: https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-docsjavascriptsmathjaxjs
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - include_exclude_files:
        include:
        exclude:
            - "notebooks/doc_ignore/"
    - mknotebooks:
        execute: !ENV [EXEC_MKNOTEBOOKS, false] # TODO(allenw): enable notebook execution once readthedocs issues are sorted.
        allow_errors: false
        enable_default_jupyter_cell_styling: false
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_signature: true
                    show_root_heading: true
                    show_root_full_path: true
                    show_if_no_docstring: true
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 2

nav:
    - 'index.md'
    - Getting Started:
        - Using TdPopcon: 'notebooks/td_popcon.ipynb'
    - Tutorials:
        - Building Modules:
            - Introduction to Modules: 'notebooks/intro_to_modules.ipynb'
            - 'Hierarchical Modules: Controller Plus Sim': 'notebooks/controller_plus_sim.ipynb'
            - Randomness and Stochasticity: 'notebooks/random_and_stochastic.ipynb'
        - Training and Validation:
            - Dataloading and Xarray-Based Pre-processing: 'notebooks/preprocess_and_dataloader.ipynb'
            - Training Modules: 'notebooks/training_td_modules.ipynb'
            - Training a Profile Predictor: 'notebooks/profile_predictor.ipynb'
        - Dev Workflow Basics: 'development_workflow.md'