# Based, in part, on the equinox mkdocs.yml file:
# https://github.com/patrick-kidger/equinox/blob/main/mkdocs.yml
theme:
    name: material
    features:
        - navigation.sections
        - toc.integrate
        - header.autohide
    palette:
        - scheme: default
          primary: deep orange
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: deep purple
          accent: indigo
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/sun-compass"

site_name: "POPSIM: Plasma OPerational SIMulation"
site_description: The documentation for POPSIM.
site_author: The POPSIM Team.
edit_uri: ""

repo_url: https://github.com/cfs-energy-internal/POPSIM
repo_name: cfs-energy-internal/POPSIM

strict: true  # Don't allow warnings during the build process

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

extra_javascript:
    # Make mathjax work: https://squidfunk.github.io/mkdocs-material/reference/math/#mathjax-docsjavascriptsmathjaxjs
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - mknotebooks
nav:
    - 'index.md'
    - Getting Started:
        - Using CometMirror: 'demos/comet_mirror.ipynb'
    - Tutorials:
        - Introduction to Modules: 'demos/intro_to_modules.ipynb'
        - 'Composite Modules: Controller Plus Sim': 'demos/controller_plus_sim.ipynb'
    - Developing: 
        - Workflow Basics: 'development_workflow.md'