[tool.poetry]
name = "popsim"
version = "0.1.0"
description = ""
authors = ["Allen Wang <allenw@mit.edu>"]
readme = "README.md"
packages = [{include = "popsim"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
diffrax = "^0.5.0"
equinox = "^0.11.2"
jax = "^0.4.20"
jaxlib = [
	{version = "^0.4.14", platform="darwin", source="pypi"},
	{version = "^0.4.19+cuda12.cudnn89", platform="linux"}
]
cfspopcon = { path = "./cfspopcon", develop = true }
interpax = {git = "https://github.com/f0uriest/interpax.git"}
optimistix = "^0.0.6"
chex = "^0.1.84"
hvplot = "^0.9.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
ruff = "^0.1.5"
pre-commit = "^3.5.0"
jupyter = "^1.0.0"
pytest-cov = "^4.1.0"
nbmake = "^1.4.6"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
fix = true
select = [
  "A", # avoid shadowing
  "B", # flake8-bugbear
  "C4", # comprehensions 
  "E", # pycodestyle Errors
  "ERA", # no commented out code
  "F", # pyflakes
  "FLY", # flynt
  "I001", # isort
  "ISC", # implicit string concatenation
  "PERF", # Perflint
  "PIE", # flake8-pie
  "PGH", # pygrep-hooks
  "PL", # pylint
  "Q", # flake8-quotes
  "RUF", # ruff builtins e.g. noqa checking
  "T10", # flake8-debugger (no breakpoint etc)
  "TCH",# type-checking imports
  "UP", # pyupgrade
  "W", # pycodestyle warnings
  ]

ignore = [
  "E501", # Never enforce line length violations, we have black for that.
  "PLR0913", #ignore limit on number of args
  "PLR2004", #ignore magic values warning, at least for now
  "C408", # use {} instead of dict(), but we use dict heavily, for now leave it
]

exclude = [
  "cfspopcon", # Don't apply ruff the the cfspopcon submodule.
  "tests", # Don't apply ruff to the tests.
]

pyupgrade.keep-runtime-typing=true
pydocstyle.convention = "google"
target-version = "py39"
line-length = 140
