from enum import Enum, IntEnum

import diffrax
import jax
import xarray as xr
from jaxtyping import Array, PyTree

import popsim.tree_util as ptu
import popsim.types as ptypes


def keypath_to_string(keypath: tuple[ptypes.PyTreeKey]) -> str:
    """Convert a keypath to a string that looks pretty.

    Args:
        keypath (tuple[ptypes.PyTreeKey]): A keypath generated by e.g. jax.tree_util.tree_leaves_with_path.

    Returns:
        str: A string representation of the keypath.
    """

    def string_func(x: ptypes.PyTreeKey) -> str:
        key = ptu.get_key(x)
        if isinstance(key, (Enum, IntEnum)):
            # For enums, return the name of the class of the enum and the name of the enum value.
            # For example, an instance of Impurity.Tungsten would return "Impurity.Tungsten".
            type_name = key.__class__.__name__
            return f"{type_name}.{key.name}"
        return str(key)

    strings = [string_func(x) for x in keypath]

    # For some reason, there is often a leading dot in the keypath.
    strings = [x.lstrip(".") for x in strings]

    # The gui also does show quantities between <>.
    strings = [x.replace("<", "").replace(">", "") for x in strings]

    # Strip away brackets.
    strings = [x.replace("[", "").replace("]", "") for x in strings]

    # Finally strip away unnecessary quotes.
    strings = [x.replace("'", "") for x in strings]

    return ".".join(strings)


def solution_to_xarray(sol: diffrax.Solution, multi_simulation: bool) -> xr.Dataset:
    """Convert a diffrax.Solution to an xarray. Thin wrapper around time_and_pytree_to_xarray.

    Args:
        sol (diffrax.Solution): diffrax.Solution object.
        multi_simulation (bool): Whether the solution contains multiple simulations.

    Returns:
        xr.Dataset: An xarray dataset.
    """
    return time_and_pytree_to_xarray(sol.ts, sol.ys, multi_simulation)


def time_and_pytree_to_xarray(time: Array, tree: PyTree[Array], multi_simulation: bool, rhogrid: Array = None) -> xr.Dataset:
    """Convert a time and a PyTree of arrays to an xarray dataset.

    Args:
        time (Array): time array. In the multi-simulation case, expect (simulation, time). In the single-simulation case, expect (time).
        tree (PyTree[Array]): PyTree of arrays. In the multi-simulatoin case, expect (simulation, time, ...). In the single-simulation case, expect (time, ...).
        multi_simulation (bool): whether the time and tree are multi-simulation.
        rhogrid (Array, optional): values of the rho grid. Defaults to None.

    Raises:
        ValueError: _description_
        ValueError: _description_

    Returns:
        xr.Dataset: An xarray dataset.
    """
    # Convert a solution to an xarray, supporting 2D arrays for "time" and "simulation".
    leaves_with_path = jax.tree_util.tree_leaves_with_path(tree)

    def convert_array(arr: Array) -> Array:
        if multi_simulation:
            if arr.ndim == 2:
                return (["simulation", "time"], arr)
            if arr.ndim == 3:
                return (["simulation", "time", "rho"], arr)
            else:
                raise ValueError(f"Array has unexpected shape {arr.shape}.")
        else:
            if arr.ndim == 1:
                return (["time"], arr)
            if arr.ndim == 2:
                return (["time", "rho"], arr)
            else:
                raise ValueError(f"Array has unexpected shape {arr.shape}.")

    variables = {keypath_to_string(keypath): convert_array(leaf) for keypath, leaf in leaves_with_path}

    # Expect time to be the same for all simulations.
    if multi_simulation and time.ndim == 2:
        assert (time == time[0]).all()

    # Expect all leaves to have the same leading dimension.
    first_leaf_data = leaves_with_path[0][1]
    assert all(leaf.shape[0] == first_leaf_data.shape[0] for _, leaf in leaves_with_path)
    coords = {"time": time[0]} if multi_simulation and time.ndim == 2 else {"time": time}

    if multi_simulation:
        coords["simulation"] = list(range(first_leaf_data.shape[0]))
    if rhogrid is not None:
        coords["rho"] = rhogrid

    dataset = xr.Dataset(data_vars=variables, coords=coords)
    return dataset
