import typing
import warnings
from enum import Enum, IntEnum
from inspect import isclass

import diffrax
import jax
import xarray as xr
from jaxtyping import Array, PyTree

import popsim.tree_util as ptu
import popsim.types as ptypes
from popsim.array_utils import jax_to_numpy_array

Coords = tuple[str, Array]
CoordSpec = typing.Union[list[Coords], Coords, None]


def keypath_to_string(keypath: tuple[ptypes.PyTreeKey]) -> str:
    """Convert a keypath to a string that looks pretty.

    Args:
        keypath (tuple[ptypes.PyTreeKey]): A keypath generated by e.g. jax.tree_util.tree_leaves_with_path.

    Returns:
        str: A string representation of the keypath.
    """

    def string_func(x: ptypes.PyTreeKey) -> str:
        key = ptu.get_key(x)
        if isinstance(key, (Enum, IntEnum)):
            # For enums, return the name of the class of the enum and the name of the enum value.
            # For example, an instance of Impurity.Tungsten would return "Impurity.Tungsten".
            type_name = key.__class__.__name__
            return f"{type_name}.{key.name}"
        return str(key)

    strings = [string_func(x) for x in keypath]

    # For some reason, there is often a leading dot in the keypath.
    strings = [x.lstrip(".") for x in strings]

    # The gui also does show quantities between <>.
    strings = [x.replace("<", "").replace(">", "") for x in strings]

    # Strip away brackets.
    strings = [x.replace("[", "").replace("]", "") for x in strings]

    # Finally strip away unnecessary quotes.
    strings = [x.replace("'", "") for x in strings]

    return ".".join(strings)


def solution_to_xarray(sol: diffrax.Solution, coord_tree: PyTree = None, multi_simulation: bool = False) -> xr.Dataset:
    """Convert a diffrax.Solution to an xarray. Thin wrapper around time_and_pytree_to_xarray.

    Args:
        sol (diffrax.Solution): diffrax.Solution object.
        coord_tree (PyTree[typing.Optional[list[Coords]]]): shadowing the tree, a PyTree of lists of tuples containing coordinate specifications.
                                                            Note the ith element of the list corresponds to the ith dimension of the array.

        multi_simulation (bool): Whether the solution contains multiple simulations.

    Returns:
        xr.Dataset: An xarray dataset.
    """
    return time_and_pytree_to_xarray(sol.ts, sol.ys, coord_tree, multi_simulation)


def convert_enums(coord_list: list[Coords]) -> list[Coords]:
    """Convert enums to strings in a list of extra coords

    Args:
        coord_spec

    Returns:
        coord_spec with enums converted to list of strings
    """
    for i, coord in enumerate(coord_list):
        coord_name, coord_labels = coord
        if isclass(coord_labels):
            if issubclass(coord_labels, Enum):
                coord_list[i] = (coord_name, list(coord_labels.__members__.keys()))
    return coord_list


def tree_and_coords_to_xarray(tree: PyTree[Array], coord_tree: PyTree[typing.Optional[list[Coords]]]) -> xr.Dataset:
    """Given a pytree of arrays and a corresponding pytree of coordinate specifications, convert to an xarray dataset.

    Args:
        tree (PyTree[Array]): PyTree of arrays containing data.
        coord_tree (PyTree[typing.Optional[list[Coords]]]): shadowing the tree, a PyTree of lists of tuples containing coordinate specifications.
                                                            Note the ith element of the list corresponds to the ith dimension of the array.

    Returns:
        xr.Dataset: dataset containing the data and coordinates.
    """

    def make_data_array(keypath: tuple[ptypes.PyTreeKey], array: Array, coord: list[Coords]) -> xr.DataArray:
        array = jax_to_numpy_array(array)
        if array.ndim == len(coord):
            # If the array and the coord have the same number of dimensions, we can just make a DataArray.
            return xr.DataArray(array, coords=convert_enums(coord))
        else:
            warnings.warn(
                f"Skipping variable {keypath_to_string(keypath)} in construction of xr.Dataset. Array and coord have different number of dimensions. Array shape: {array.shape}, coord shape: {len(coord)}.",
                stacklevel=2,
            )
            return None

    # Construct a tree of DataArrays.
    da_tree = jax.tree_util.tree_map_with_path(make_data_array, tree, coord_tree)

    # Convert the tree of DataArrays to a dictionary of DataArrays.
    # Use the keypath_to_string on the keypath to generate a unique name for each DataArray.
    leaves_with_path = jax.tree_util.tree_leaves_with_path(da_tree)
    dict_of_da = {keypath_to_string(keypath): leaf for keypath, leaf in leaves_with_path if leaf is not None}

    # Convert to a Dataset.
    ds = xr.Dataset(dict_of_da)
    return ds


def time_and_pytree_to_xarray(
    time: Array, tree: PyTree[Array], extra_coord_tree: PyTree[CoordSpec] = None, multi_simulation: bool = False
) -> xr.Dataset:
    """Convert a time and a PyTree of arrays to an xarray dataset. In the multi-simulation case, assign numbered names to the simulations.

    Assumptions:
        - In the multi_simulation = False case, arrays are expected to have shape (time, ...).
        - In the multi_simulation = True case, arrays are expected to have shape (simulation, time, ...).
        - In the multi_simulation = True case, the time array is expected to be the same for all simulations.

    Args:
        time (Array): time array. In the multi-simulation case, expect (simulation, time). In the single-simulation case, expect (time).
        tree (PyTree[Array]): PyTree of arrays. In the multi-simulatoin case, expect (simulation, time, ...). In the single-simulation case, expect (time, ...).
        extra_coord_tree (PyTree[CoordSpec]): PyTree of extra coordinates for the arrays.
        multi_simulation (bool): whether the time and tree are multi-simulation.

    Returns:
        xr.Dataset: An xarray dataset.
    """

    if multi_simulation:
        assert time.ndim in (2, 1)
        # If time is 1D, assume it applies to all simulations.
        if time.ndim == 2:
            # Currently we only support the case where the time array is the same for all simulations.
            assert (time == time[0]).all()

        # Check that every array has the same number of simulations.
        nsims_tree = jax.tree.map(lambda x: x.shape[0], tree)
        tree_leaves = jax.tree.leaves(nsims_tree)
        if len(set(tree_leaves)) > 1:
            raise ValueError("In multi-simulation mode, all arrays must have the same number of simulations.")
        nsims = tree_leaves[0]
    else:
        nsims = 1

    # Define the time base for all dataarray instances.
    time_base = time[0] if multi_simulation and time.ndim == 2 else time
    time_base = time_base.squeeze()

    def make_coords_for_array(_, extra_coords):
        # Why the dummy first argument?
        # We don't need the array data to construct the coordinates, but
        # performing a multi-map avoids the issue of tree.map treating
        # tuples as tree nodes themselves. Thus, the multi-map maps the function
        # to the depth of the leaves of the original array.
        if extra_coords is None:
            # Define as empty list so unpacking works down the line.
            extra_coords = []
        elif isinstance(extra_coords, tuple):
            # Wrap the tuple in a list.
            extra_coords = [extra_coords]
        elif isinstance(extra_coords, list):
            pass
        else:
            raise ValueError(f"extra_coords must be a tuple, list or None, got {type(extra_coords)}.")

        if multi_simulation:
            simulation_numbers = range(nsims)
            return [("simulation", simulation_numbers), ("time", time_base), *extra_coords]
        else:
            return [("time", time_base), *extra_coords]

    # Construct the coordnates tree.
    extra_coord_tree = jax.tree.map(lambda _: None, tree) if extra_coord_tree is None else extra_coord_tree
    coord_tree = jax.tree.map(make_coords_for_array, tree, extra_coord_tree)

    # Construct the dataset.
    ds = tree_and_coords_to_xarray(tree, coord_tree)
    return ds
