import jax
import pytest
from popsim.tests.fixtures import cmod_test_dataset, reduced_cmod_test_dataset
from popsim.ml.dataloading import make_dataloaders, make_standard_dataloaders, make_time_dep_dataloader, make_time_indep_dataloader, XarrayPreppedDataset, DEFAULT_SAMPLE_DIM
import numpy as np
from copy import deepcopy
import xarray as xr
from popsim.ml._types import TrainingMetadata

def _run_dl_checks(dl, batch_size, expected_n_samps, shuffle, segment_length, convert_xr):
    """Generic function to check the properties of a dataloader generated by make_time_dep_dataloader and make_time_indep_dataloader."""
    # "None" batch size should be equivalent to loading all samples in a single batch.
    batch_size_handle_none = batch_size if batch_size is not None else expected_n_samps

    # The number of batches should be the number of samples divided by the batch size rounded up.
    expected_n_batches = max(1, np.ceil(expected_n_samps / batch_size_handle_none).astype(int))
    assert len(dl) == expected_n_batches

    # For each batch, check it is an XarrayPreppedDataset and that the sizes are correct.
    first_batches = []
    for idx, batch in enumerate(dl):
        assert isinstance(batch, XarrayPreppedDataset)

        # Make sure the leading dimension is the sample dimension.
        assert list(batch.ds.sizes.keys())[0] == DEFAULT_SAMPLE_DIM

        # Nominally, the batch size is just "batch_size_handle_none", but the last batch may be smaller.
        expected_sample_size = min(batch_size_handle_none, expected_n_samps - idx * batch_size_handle_none)

        if segment_length is not None:
            assert dict(batch.ds.sizes) == {DEFAULT_SAMPLE_DIM: expected_sample_size, 'time_slice_input': segment_length}
        else:
            assert batch.ds.sizes[DEFAULT_SAMPLE_DIM] == expected_sample_size

        inputs, targets = batch.get_inputs_and_targets()

        if convert_xr:
            assert isinstance(targets, dict)
        else:
            assert isinstance(targets, xr.Dataset)
        
        first_batches.append(deepcopy(batch))

    # Iterate through the dataloader again to check that the "shuffle" flag works as intended.
    second_round_batches = [batch for batch in dl]

    if shuffle:
        assert first_batches != second_round_batches
    else:
        assert first_batches == second_round_batches

@pytest.mark.parametrize("segmenting_case", [{"seg_length": 250, "seg_overlap": 25, "expected_n_samps" : 681}, {"seg_length": 250, "seg_overlap": 0, "expected_n_samps" : 600},
                                             {"seg_length": None, "seg_overlap": 0, "expected_n_samps" : 99}])
@pytest.mark.parametrize("batch_size", [None, 1, 64, 1024, np.iinfo(np.int32).max])
@pytest.mark.parametrize("shuffle", [True, False])
@pytest.mark.parametrize("convert_xr_to_jnp", [True, False])
def test_make_time_dep_dataloader(reduced_cmod_test_dataset, segmenting_case, batch_size, shuffle, convert_xr_to_jnp):
    ds, state_init_vars, input_vars, target_vars = reduced_cmod_test_dataset

    # expected_n_samps were determined by manually checking the dataset.
    segment_length, segment_overlap, expected_n_samps = segmenting_case["seg_length"], segmenting_case["seg_overlap"], segmenting_case["expected_n_samps"]
    dl = make_time_dep_dataloader(
        ds=ds,
        time_coord="time",
        episode_coord="shot",
        state_init_vars=state_init_vars,
        input_vars=input_vars,
        target_vars=target_vars,
        convert_xr_to_jnp=convert_xr_to_jnp,
        segment_length=segment_length,
        segment_overlap=segment_overlap,
        batch_size=batch_size,
        shuffle=shuffle
    )

    _run_dl_checks(
        dl=dl, 
        batch_size=batch_size, 
        expected_n_samps=expected_n_samps, 
        shuffle=shuffle,
        segment_length=segment_length,
        convert_xr=convert_xr_to_jnp
    )

@pytest.mark.parametrize("batch_size", [None, 1024, np.iinfo(np.int32).max])
@pytest.mark.parametrize("shuffle", [True, False])
@pytest.mark.parametrize("convert_xr_to_jnp", [True, False])
def test_make_time_indep_dataloader(reduced_cmod_test_dataset, batch_size, shuffle, convert_xr_to_jnp):
    ds, _, _, _ = reduced_cmod_test_dataset
    expected_n_samps = 151046 # Manually checked the dataset.
    dl = make_time_indep_dataloader(
        ds=ds,
        time_coord="time",
        episode_coord="shot",
        input_vars=["p_rad", "ip", "n_e"],
        target_vars=["Wmhd"],
        convert_xr_to_jnp=convert_xr_to_jnp,
        batch_size=batch_size,
        shuffle=shuffle
    )

    _run_dl_checks(
        dl=dl, 
        batch_size=batch_size, 
        expected_n_samps=expected_n_samps, 
        shuffle=shuffle,
        segment_length=None,
        convert_xr=convert_xr_to_jnp
    )

def test_prepped_ds_error(reduced_cmod_test_dataset):
    """Test that assigning the wrong sample coordinate to the TrainingMetadata raises an error."""
    ds, _, _, _ = reduced_cmod_test_dataset

    data_var_names = list(ds.data_vars.keys())

    train_meta = TrainingMetadata(
        convert_xr_to_jnp=False,
        sample_coord=data_var_names[0], # Data vars are 2D, so this should create an error.
        sample_dim="shot",
        input_vars=data_var_names[:2],
        target_vars=data_var_names[2:4],
        time_dep_metadata=TrainingMetadata.TimeDepMetadata(
            state_init_vars=data_var_names[4:],
            time_coord="time",
            time_dim="time",
        )
    )


    with pytest.raises(ValueError):
        dataset = XarrayPreppedDataset(ds, train_meta)

@pytest.mark.parametrize("batch_size", [None, 1024, np.iinfo(np.int32).max])
@pytest.mark.parametrize("time_dependent", [True, False])
@pytest.mark.parametrize("segment_length", [None, 100])
def test_dl_limit_size_cmod(reduced_cmod_test_dataset, batch_size, time_dependent, segment_length):
    """Tests for limiting dimensions in the dataloader in a typical workflow"""
    ds, state_init_vars, input_vars, target_vars = reduced_cmod_test_dataset

    convert_xr = True
    shuffle = True

    if time_dependent:
        dl = make_time_dep_dataloader(
            ds=ds,
            time_coord="time",
            episode_coord="shot",
            state_init_vars=state_init_vars,
            input_vars=input_vars,
            target_vars=target_vars,
            batch_size=batch_size,
            convert_xr_to_jnp=convert_xr,
            segment_length=segment_length,
            shuffle=shuffle
        )
    else:
        dl = make_time_indep_dataloader(
            ds=ds,
            time_coord="time",
            episode_coord="shot",
            input_vars=input_vars,
            target_vars=target_vars,
            batch_size=batch_size,
            convert_xr_to_jnp=convert_xr,
            shuffle=shuffle
        )

    # Check that we can limit by the episode coord
    lim_dl = dl.limit_size(size=10, coord="shot")
    assert np.unique(lim_dl.ds.shot).size == 10

    if time_dependent:
        # If a short segment length is provided, there should be more samples than shots
        if segment_length and (segment_length <= lim_dl.ds.sizes["time_slice_input"]):
            assert lim_dl.ds.sizes["sample"] > 10

        # Check that we can limit by the time segment dimension
        lim_dl = dl.limit_size(size=10, coord="time_slice_input")
        assert np.unique(lim_dl.ds.time_slice_input).size == 10
    else:
        # Check that we can limit by the sample dimension
        lim_dl = dl.limit_size(size=10, coord="sample")
        assert np.unique(lim_dl.ds.sample).size == 10
        _run_dl_checks(lim_dl, batch_size=batch_size, expected_n_samps=10, shuffle=shuffle, segment_length=None, convert_xr=convert_xr)

@pytest.mark.parametrize("time_dependent", [True, False])
def test_dl_limit_size_constructed(time_dependent):
    """More rigorous testing of the limit_size method, covering limit by every coordinate and dimension"""
    num_shots = 4
    num_times = 30
    ds = xr.Dataset(
        {
            "p_rad": (("shot", "time_slice"), np.random.rand(num_shots, num_times)),
            "ip": (("shot", "time_slice"), np.random.rand(num_shots, num_times)),
            "n_e": (("shot", "time_slice"), np.random.rand(num_shots, num_times)),
            "Wmhd": (("shot", "time_slice"), np.random.rand(num_shots, num_times)),
        },
        coords={
            "shot": np.arange(num_shots),
            "time_slice": np.arange(num_times),
            "time": (("shot", "time_slice"), np.tile(np.arange(num_times)*0.001, (num_shots, 1))),
        }
    )
    state_init_vars = ["Wmhd"]
    target_vars = ["p_rad"]
    input_vars = ["ip", "n_e"]

    convert_xr = True
    shuffle = False
    segment_length = 10
    batch_size = None

    if time_dependent:
        dl = make_time_dep_dataloader(
            ds=ds,
            time_coord="time",
            episode_coord="shot",
            state_init_vars=state_init_vars,
            input_vars=input_vars,
            target_vars=target_vars,
            convert_xr_to_jnp=convert_xr,
            segment_length=segment_length,
            batch_size=batch_size,
            shuffle=shuffle
        )
    else:
        dl = make_time_indep_dataloader(
            ds=ds,
            time_coord="time",
            episode_coord="shot",
            input_vars=input_vars,
            target_vars=target_vars,
            convert_xr_to_jnp=convert_xr,
            shuffle=shuffle
        )

    for coord in list(dl.ds.coords) + list(dl.ds.dims):
        lim_dl = dl.limit_size(size=2, coord=coord)
        assert np.unique(lim_dl.ds[coord]).size == 2

def test_prng(reduced_cmod_test_dataset):
    ds, _, _, _ = reduced_cmod_test_dataset
    dl = make_time_indep_dataloader(
        ds=ds,
        time_coord="time",
        episode_coord="shot",
        input_vars=["p_rad", "ip", "n_e"],
        target_vars=["Wmhd"],
        convert_xr_to_jnp=True,
        batch_size=512,
        shuffle=True,
        generate_prng=True
    )
    
    # Check that when we grab the next batch, there is a "prng_key" variable in the dataset.
    batch = next(iter(dl))
    assert "prng_key" in batch.ds
    prng_key1 = dl.ds["prng_key"].data
    
    _ = next(iter(dl))
    prng_key2 = dl.ds["prng_key"].data
    
    # Check that the prng keys are different for different batches.
    assert not np.array_equal(prng_key1, prng_key2)

@pytest.mark.parametrize("method", ["drop_slice_all", "drop_slice_any", "drop_segment"])
def test_time_dep_dl_nan_handling_no_nan(method):
    """Test that the dataloader returns the same dataset when there are no NaNs to handle for all three NaN handling methods."""
    ds_orig = xr.Dataset(
        data_vars={
            "input_1": (("shot", "time_idx"), np.array([[1.0, 1.1, 1.2, 1.3], [1.0, 1.1, 1.2, 1.3]])),
            "input_2": (("shot", "time_idx"), np.array([[2.0, 2.1, 2.2, 2.3], [2.0, 2.1, 2.2, 2.3]])),
            "target_0D": (("shot", "time_idx"), np.array([[3.0, 3.1, 3.2, 3.3], [3.0, 3.1, 3.2, 3.3]])),
            "target_1D": (("shot", "time_idx", "rho"), np.array([[[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]]])),

        },
        coords={
            "time": (("shot", "time_idx"), np.array([[0.0, 0.1, 0.2, 0.3], [0.0, 0.1, 0.2, 0.3]])),
            "shot": [1, 2],
            "rho": [0, 0.5, 1],
        },
    )

    ds_expected = xr.Dataset(
        data_vars={
            "input_1": (("sample", "time_idx_input"), np.array([[1.0, 1.1, 1.2, 1.3], [1.0, 1.1, 1.2, 1.3]])),
            "input_2": (("sample", "time_idx_input"), np.array([[2.0, 2.1, 2.2, 2.3], [2.0, 2.1, 2.2, 2.3]])),
            "target_0D": (("sample", "time_idx_input"), np.array([[3.0, 3.1, 3.2, 3.3], [3.0, 3.1, 3.2, 3.3]])),
            "target_1D": (("sample", "time_idx_input", "rho_input"), np.array([[[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]]])),
        },
        coords={
            "time": (("sample", "time_idx_input"), np.array([[0.0, 0.1, 0.2, 0.3], [0.0, 0.1, 0.2, 0.3]])),
            "input_batch": ("sample", [0, 0]),
            "shot": ("sample", [1, 2]),
            "rho": (("rho_input"), np.array([0, 0.5, 1])),
        },
    )

    dl = make_time_dep_dataloader(
        ds=ds_orig,
        time_coord="time",
        episode_coord="shot",
        state_init_vars=[],
        input_vars=["input_1", "input_2"],
        target_vars=["target_0D", "target_1D"],
        convert_xr_to_jnp=False,
        batch_size=None,
        shuffle=False,
        nan_handling=method
    )

    # Check that the resulting dataloader dataset is the same as the original, since there are no NaNs to handle.
    for var in list(ds_expected.data_vars) + list(ds_expected.coords):
        assert np.allclose(dl.ds[var].data, ds_expected[var].data, atol=1e-06)


@pytest.mark.parametrize("method", ["drop_slice_all", "drop_slice_any", "drop_segment"])
def test_time_dep_dl_nan_handling_start_timeslice(method):
    """Test that the dataloader correctly handles NaNs at the start of a time slice for all three NaN handling methods.
    The NaN handling method shouldn't really do anything in this case since it's similar to the shift_time_to_not_nan"""
    ds_orig = xr.Dataset(
        data_vars={
            "input_1": (("shot", "time_idx"), np.array([[np.nan, 1.1, 1.2, 1.3], [1.0, 1.1, 1.2, 1.3]])),
            "input_2": (("shot", "time_idx"), np.array([[np.nan, 2.1, 2.2, 2.3], [2.0, 2.1, 2.2, 2.3]])),
            "target_0D": (("shot", "time_idx"), np.array([[np.nan, 3.1, 3.2, 3.3], [3.0, 3.1, 3.2, 3.3]])),
            "target_1D": (("shot", "time_idx", "rho"), np.array([[[np.nan, np.nan, np.nan], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]]])),

        },
        coords={
            "time": (("shot", "time_idx"), np.array([[0.0, 0.1, 0.2, 0.3], [0.0, 0.1, 0.2, 0.3]])),
            "shot": [1, 2],
            "rho": [0, 0.5, 1],
        },
    )

    ds_expected = xr.Dataset(
        data_vars={
            "input_1": (("shot", "time_idx"), np.array([[1.1, 1.2, 1.3, 1.3], [1.0, 1.1, 1.2, 1.3]])),
            "input_2": (("shot", "time_idx"), np.array([[2.1, 2.2, 2.3, 2.3], [2.0, 2.1, 2.2, 2.3]])),
            "target_0D": (("shot", "time_idx"), np.array([[3.1, 3.2, 3.3, 3.3], [3.0, 3.1, 3.2, 3.3]])),
            "target_1D": (("shot", "time_idx", "rho"), np.array([[[4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32], [4.30, 4.31, 4.32]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]]])),

        },
        coords={
            "time": (("shot", "time_idx"), np.array([[0.1, 0.2, 0.3, 0.3], [0.0, 0.1, 0.2, 0.3]])),
            "shot": [1, 2],
            "rho": [0, 0.5, 1],
        },
    )

    dl = make_time_dep_dataloader(
        ds=ds_orig,
        time_coord="time",
        episode_coord="shot",
        state_init_vars=[],
        input_vars=["input_1", "input_2"],
        target_vars=["target_0D", "target_1D"],
        convert_xr_to_jnp=False,
        batch_size=None,
        shuffle=False,
        nan_handling=method
    )

    # Check that the resulting dataloader dataset matches the expected dataset for the given NaN handling method.
    for var in list(ds_expected.data_vars) + list(ds_expected.coords):
        assert np.allclose(dl.ds[var].data, ds_expected[var].data, equal_nan=True, atol=1e-06)


@pytest.mark.parametrize("method", ["drop_slice_all", "drop_slice_any", "drop_segment"])
def test_time_dep_dl_nan_handling_end_timeslice(method):
    """Test that the dataloader correctly handles NaNs at the end of a time slice for all three NaN handling methods.
    The NaN handling shouldn't really do anything in this case since it's similar to the trim_time_to_not_nan"""
    ds_orig = xr.Dataset(
        data_vars={
            "input_1": (("shot", "time_idx"), np.array([[1.0, 1.1, 1.2, np.nan], [1.0, 1.1, 1.2, np.nan]])),
            "input_2": (("shot", "time_idx"), np.array([[2.0, 2.1, 2.2, np.nan], [2.0, 2.1, 2.2, np.nan]])),
            "target_0D": (("shot", "time_idx"), np.array([[3.0, 3.1, 3.2, np.nan], [3.0, 3.1, 3.2, np.nan]])),
            "target_1D": (("shot", "time_idx", "rho"), np.array([[[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [np.nan, np.nan, np.nan]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [np.nan, np.nan, np.nan]]])),

        },
        coords={
            # End timeslice with everything nan, and end timeslice with everything except time nan
            # In both cases the final time slice should be completely dropped
            "time": (("shot", "time_idx"), np.array([[0.0, 0.1, 0.2, np.nan], [0.0, 0.1, 0.2, 0.3]])),
            "shot": [1, 2],
            "rho": [0, 0.5, 1],
        },
    )

    ds_expected = xr.Dataset(
        data_vars={
            "input_1": (("shot", "time_idx"), np.array([[1.0, 1.1, 1.2], [1.0, 1.1, 1.2]])),
            "input_2": (("shot", "time_idx"), np.array([[2.0, 2.1, 2.2], [2.0, 2.1, 2.2]])),
            "target_0D": (("shot", "time_idx"), np.array([[3.0, 3.1, 3.2], [3.0, 3.1, 3.2]])),
            "target_1D": (("shot", "time_idx", "rho"), np.array([[[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22]]])),

        },
        coords={
            "time": (("shot", "time_idx"), np.array([[0.0, 0.1, 0.2], [0.0, 0.1, 0.2]])),
            "shot": [1, 2],
            "rho": [0, 0.5, 1],
        },
    )

    dl = make_time_dep_dataloader(
        ds=ds_orig,
        time_coord="time",
        episode_coord="shot",
        state_init_vars=[],
        input_vars=["input_1", "input_2"],
        target_vars=["target_0D", "target_1D"],
        convert_xr_to_jnp=False,
        batch_size=None,
        shuffle=False,
        nan_handling=method
    )

    # Check that the resulting dataloader dataset matches the expected dataset for the given NaN handling method.
    for var in list(ds_expected.data_vars) + list(ds_expected.coords):
        assert np.allclose(dl.ds[var].data, ds_expected[var].data, equal_nan=True, atol=1e-06)

@pytest.mark.parametrize("method, expected", [
    [
        "drop_slice_all",
        xr.Dataset(
            data_vars={
                "input_1": (("sample", "time_idx_input"), np.array([[1.0, 1.3, 1.3, 1.3], [1.0, 1.1, 1.2, 1.3]])),
                "input_2": (("sample", "time_idx_input"), np.array([[2.0, 2.3, 2.3, 2.3], [2.0, 2.1, 2.2, 2.3]])),
                "target_0D": (("sample", "time_idx_input"), np.array([[3.0, 3.3, 3.3, 3.3], [3.0, 3.1, 3.2, 3.3]])),
                "target_1D": (("sample", "time_idx_input", "rho_input"), np.array([[[4.00, 4.01, 4.02], [4.30, 4.31, 4.32], [4.30, 4.31, 4.32], [4.30, 4.31, 4.32]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]]])),
            },
            coords={
                "time": (("sample", "time_idx_input"), np.array([[0.0, 0.3, 0.3, 0.3], [0.0, 0.1, 0.2, 0.3]])),
                "input_batch": ("sample", [0, 0]),
                "shot": ("sample", [1, 2]),
                "rho": (("rho_input"), np.array([0, 0.5, 1])),
            },
        )
    ],
    [
        "drop_slice_any",
        xr.Dataset(
            data_vars={
                "input_1": (("sample", "time_idx_input"), np.array([[1.0, 1.3, 1.3, 1.3], [1.0, 1.1, 1.2, 1.3]])),
                "input_2": (("sample", "time_idx_input"), np.array([[2.0, 2.3, 2.3, 2.3], [2.0, 2.1, 2.2, 2.3]])),
                "target_0D": (("sample", "time_idx_input"), np.array([[3.0, 3.3, 3.3, 3.3], [3.0, 3.1, 3.2, 3.3]])),
                "target_1D": (("sample", "time_idx_input", "rho_input"), np.array([[[4.00, 4.01, 4.02], [4.30, 4.31, 4.32], [4.30, 4.31, 4.32], [4.30, 4.31, 4.32]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]]])),
            },
            coords={
                "time": (("sample", "time_idx_input"), np.array([[0.0, 0.3, 0.3, 0.3], [0.0, 0.1, 0.2, 0.3]])),
                "input_batch": ("sample", [0, 0]),
                "shot": ("sample", [1, 2]),
                "rho": (("rho_input"), np.array([0, 0.5, 1])),
            },
        )
    ],
    [
        "drop_segment",
        xr.Dataset(
            data_vars={
                "input_1": (("sample", "time_idx_input"), np.array([[1.0, 1.1, 1.2, 1.3]])),
                "input_2": (("sample", "time_idx_input"), np.array([[2.0, 2.1, 2.2, 2.3]])),
                "target_0D": (("sample", "time_idx_input"), np.array([[3.0, 3.1, 3.2, 3.3]])),
                "target_1D": (("sample", "time_idx_input", "rho_input"), np.array([[[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]]])),
            },
            coords={
                "time": (("sample", "time_idx_input"), np.array([[0.0, 0.1, 0.2, 0.3]])),
                "input_batch": ("sample", [0]),
                "shot": ("sample", [2]),
                "rho": (("rho_input"), np.array([0, 0.5, 1])),
            },
        )
    ],
])
def test_time_dep_dl_nan_handling_middle_timeslices(method, expected):
    """Test that the dataloader correctly handles NaNs in the middle of a time slice for all three NaN handling methods.
    drop_slice_all and drop_slice_any should give the same result and lead to a time skip and forward-fill at the end
    drop_segment should lead to an episode being dropped
    """
    ds_orig = xr.Dataset(
        data_vars={
            "input_1": (("shot", "time_idx"), np.array([[1.0, np.nan, np.nan, 1.3], [1.0, 1.1, 1.2, 1.3]])),
            "input_2": (("shot", "time_idx"), np.array([[2.0, np.nan, np.nan, 2.3], [2.0, 2.1, 2.2, 2.3]])),
            "target_0D": (("shot", "time_idx"), np.array([[3.0, np.nan, np.nan, 3.3], [3.0, 3.1, 3.2, 3.3]])),
            "target_1D": (("shot", "time_idx", "rho"), np.array([[[4.00, 4.01, 4.02], [np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan], [4.30, 4.31, 4.32]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]]])),

        },
        coords={
            "time": (("shot", "time_idx"), np.array([[0.0, 0.1, 0.2, 0.3], [0.0, 0.1, 0.2, 0.3]])),
            "shot": [1, 2],
            "rho": [0, 0.5, 1],
        },
    )

    dl = make_time_dep_dataloader(
        ds=ds_orig,
        time_coord="time",
        episode_coord="shot",
        state_init_vars=[],
        input_vars=["input_1", "input_2"],
        target_vars=["target_0D", "target_1D"],
        convert_xr_to_jnp=False,
        batch_size=None,
        shuffle=False,
        nan_handling=method
    )

    # Check that the resulting dataloader dataset matches the expected dataset for the given NaN handling method.
    for var in list(expected.data_vars) + list(expected.coords):
        assert np.allclose(dl.ds[var].data, expected[var].data, equal_nan=True, atol=1e-06)


@pytest.mark.parametrize("method, expected", [
    [
        "drop_slice_all",
        "value_error",
    ],
    [
        "drop_slice_any",
        xr.Dataset(
            data_vars={
                "input_1": (("sample", "time_idx_input"), np.array([[1.0, 1.2, 1.3], [1.0, 1.1, 1.3]])),
                "input_2": (("sample", "time_idx_input"), np.array([[2.0, 2.2, 2.3], [2.0, 2.1, 2.3]])),
                "target_0D": (("sample", "time_idx_input"), np.array([[3.0, 3.2, 3.3], [3.0, 3.1, 3.3]])),
                "target_1D": (("sample", "time_idx_input", "rho_input"), np.array([[[4.00, 4.01, 4.02], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.30, 4.31, 4.32]]])),
            },
            coords={
                "time": (("sample", "time_idx_input"), np.array([[0.0, 0.2, 0.3], [0.0, 0.1, 0.3]])),
                "input_batch": ("sample", [0, 0]),
                "shot": ("sample", [1, 2]),
                "rho": (("rho_input"), np.array([0, 0.5, 1])),
            },
        )
    ],
    [
        "drop_segment",
        "value_error",
    ],
])
def test_time_dep_dl_nan_handling_intermittent(method, expected):
    """Test that the dataloader correctly handles NaNs that are intermittent across time slices for all three NaN handling methods.
    
    drop_slice_all should raise a ValueError since the NaNs only appear in a single variable
    drop_slice_any should have time skips and samples that are shorter than original since they wind up the same length
    drop_segment should raise a ValueError since both episodes have NaNs
    """
    ds_orig = xr.Dataset(
        data_vars={
            "input_1": (("shot", "time_idx"), np.array([[1.0, np.nan, 1.2, 1.3], [1.0, 1.1, 1.2, 1.3]])),
            "input_2": (("shot", "time_idx"), np.array([[2.0, 2.1, 2.2, 2.3], [2.0, 2.1, 2.2, 2.3]])),
            "target_0D": (("shot", "time_idx"), np.array([[3.0, 3.1, 3.2, 3.3], [3.0, 3.1, 3.2, 3.3]])),
            "target_1D": (("shot", "time_idx", "rho"), np.array([[[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, 4.21, 4.22], [4.30, 4.31, 4.32]], [[4.00, 4.01, 4.02], [4.10, 4.11, 4.12], [4.20, np.nan, 4.22], [4.30, 4.31, 4.32]]])),

        },
        coords={
            "time": (("shot", "time_idx"), np.array([[0.0, 0.1, 0.2, 0.3], [0.0, 0.1, 0.2, 0.3]])),
            "shot": [1, 2],
            "rho": [0, 0.5, 1],
        },
    )

    if isinstance(expected, str) and expected == "value_error":
        with pytest.raises(ValueError):
            dl = make_time_dep_dataloader(
                ds=ds_orig,
                time_coord="time",
                episode_coord="shot",
                state_init_vars=[],
                input_vars=["input_1", "input_2"],
                target_vars=["target_0D", "target_1D"],
                convert_xr_to_jnp=False,
                batch_size=None,
                shuffle=False,
                nan_handling=method
            )
    else:
        dl = make_time_dep_dataloader(
            ds=ds_orig,
            time_coord="time",
            episode_coord="shot",
            state_init_vars=[],
            input_vars=["input_1", "input_2"],
            target_vars=["target_0D", "target_1D"],
            convert_xr_to_jnp=False,
            batch_size=None,
            shuffle=False,
            nan_handling=method
        )

        # Check that the resulting dataloader dataset matches the expected dataset for the given NaN handling method.
        for var in list(expected.data_vars) + list(expected.coords):
            assert np.allclose(dl.ds[var].data, expected[var].data, equal_nan=True, atol=1e-06)


@pytest.mark.parametrize("time_dep", [True, False])
def test_make_dataloaders_handles_list_arguments(time_dep: bool):
    """Verify make_dataloaders applies list-valued args to the matching dataset index."""
    ds_full = xr.Dataset(
        {
            "p_rad": (("shot", "time_slice"), np.random.rand(4, 6)),
            "ip": (("shot", "time_slice"), np.random.rand(4, 6)),
            "n_e": (("shot", "time_slice"), np.random.rand(4, 6)),
            "Wmhd": (("shot", "time_slice"), np.random.rand(4, 6)),
        },
        coords={
            "shot": np.arange(4),
            "time_slice": np.arange(6),
            "time": (("shot", "time_slice"), np.tile(np.arange(6) * 0.001, (4, 1))),
        },
    )

    datasets = [ds_full.isel(shot=slice(0, 2)), ds_full.isel(shot=slice(2, 4))]
    batch_sizes = [1, 2]
    shuffles = [False, True]
    nan_handling = ["drop_slice_all", "drop_slice_all"]

    if time_dep:
        segment_lengths = [3, None]
        segment_overlaps = [1, 0]

        dls = make_dataloaders(
            datasets=datasets,
            time_coord="time",
            episode_coord="shot",
            state_init_vars=["Wmhd"],
            input_vars=["ip", "n_e"],
            target_vars=["p_rad"],
            convert_xr_to_jnp=False,
            batch_size=batch_sizes,
            segment_length=segment_lengths,
            segment_overlap=segment_overlaps,
            shuffle=shuffles,
            nan_handling=nan_handling,
        )

        expected_dls = [
            make_time_dep_dataloader(
                ds=ds,
                time_coord="time",
                episode_coord="shot",
                state_init_vars=["Wmhd"],
                input_vars=["ip", "n_e"],
                target_vars=["p_rad"],
                convert_xr_to_jnp=False,
                batch_size=batch_size,
                segment_length=segment_length,
                segment_overlap=segment_overlap,
                shuffle=shuffle,
                nan_handling=nan_method,
            )
            for ds, batch_size, segment_length, segment_overlap, shuffle, nan_method in zip(
                datasets, batch_sizes, segment_lengths, segment_overlaps, shuffles, nan_handling, strict=False
            )
        ]

        with pytest.raises(ValueError):
            make_dataloaders(
                datasets=datasets,
                time_coord="time",
                episode_coord="shot",
                state_init_vars=["Wmhd"],
                input_vars=["ip", "n_e"],
                target_vars=["p_rad"],
                convert_xr_to_jnp=False,
                batch_size=[1],  # Incorrect length
                segment_length=segment_lengths,
                segment_overlap=segment_overlaps,
                shuffle=shuffles,
                nan_handling=nan_handling,
            )
    else:
        dls = make_dataloaders(
            datasets=datasets,
            time_coord="time",
            episode_coord="shot",
            input_vars=["ip", "n_e"],
            target_vars=["p_rad"],
            convert_xr_to_jnp=False,
            batch_size=batch_sizes,
            shuffle=shuffles,
        )

        expected_dls = [
            make_time_indep_dataloader(
                ds=ds,
                time_coord="time",
                episode_coord="shot",
                input_vars=["ip", "n_e"],
                target_vars=["p_rad"],
                convert_xr_to_jnp=False,
                batch_size=batch_size,
                shuffle=shuffle,
            )
            for ds, batch_size, shuffle, in zip(
                datasets, batch_sizes, shuffles, strict=False
            )
        ]

    assert len(dls) == len(expected_dls)
    for created_dl, expected_dl in zip(dls, expected_dls, strict=False):
        assert created_dl.batch_size == expected_dl.batch_size
        assert created_dl.shuffle == expected_dl.shuffle
        assert len(created_dl) == len(expected_dl)
        assert created_dl.ds.equals(expected_dl.ds)

        created_first_batch = next(iter(created_dl))
        expected_first_batch = next(iter(expected_dl))
        assert created_first_batch == expected_first_batch


def test_make_standard_dataloaders():
    """Verify make_standard_dataloaders completes without error"""
    num_shots = 5
    ds_full = xr.Dataset(
        {
            "p_rad": (("shot", "time_slice"), np.random.rand(num_shots, 6)),
            "ip": (("shot", "time_slice"), np.random.rand(num_shots, 6)),
            "n_e": (("shot", "time_slice"), np.random.rand(num_shots, 6)),
            "Wmhd": (("shot", "time_slice"), np.random.rand(num_shots, 6)),
        },
        coords={
            "shot": np.arange(num_shots),
            "time_slice": np.arange(6),
            "time": (("shot", "time_slice"), np.tile(np.arange(6) * 0.001, (num_shots, 1))),
        },
    )

    split_fracs = [0.6, 0.4]
    datasets = [ds_full.isel(shot=slice(0, 3)), ds_full.isel(shot=slice(3, 5))]
    batch_sizes = [1, 2]
    segment_lengths = [3, None]
    segment_overlaps = [1, 0]
    shuffles = [True, False]
    nan_handling = ["drop_slice_all", "drop_slice_all"]

    dls = make_standard_dataloaders(
        ds=ds_full,
        time_coord="time",
        episode_coord="shot",
        state_init_vars=["Wmhd"],
        input_vars=["ip", "n_e"],
        target_vars=["p_rad"],
        split_fracs=split_fracs,
        convert_xr_to_jnp=False,
        batch_size=batch_sizes,
        segment_length=segment_lengths,
        segment_overlap=segment_overlaps,
        nan_handling=nan_handling,
    )

    expected_dls = [
        make_time_dep_dataloader(
            ds=ds,
            time_coord="time",
            episode_coord="shot",
            state_init_vars=["Wmhd"],
            input_vars=["ip", "n_e"],
            target_vars=["p_rad"],
            convert_xr_to_jnp=False,
            batch_size=batch_size,
            segment_length=segment_length,
            segment_overlap=segment_overlap,
            shuffle=shuffle,
            nan_handling=nan_method,
        )
        for ds, batch_size, segment_length, segment_overlap, shuffle, nan_method in zip(
            datasets, batch_sizes, segment_lengths, segment_overlaps, shuffles, nan_handling, strict=False
        )
    ]

    assert len(dls) == len(expected_dls)
    for created_dl, expected_dl in zip(dls, expected_dls, strict=False):
        assert created_dl.batch_size == expected_dl.batch_size
        assert created_dl.shuffle == expected_dl.shuffle
        assert len(created_dl) == len(expected_dl)


@pytest.mark.parametrize("time_dep", [True, False])
def test_dl_keeps_coords(reduced_cmod_test_dataset, time_dep: bool):
    """Ensure dataloader creation doesn't lose the original dataset's coords and the data hasn't been moved relative to the coords"""
    ds_orig, state_init_vars, input_vars, target_vars = reduced_cmod_test_dataset

    if time_dep:
        dl = make_time_dep_dataloader(
            ds=ds_orig,
            time_coord="time",
            episode_coord="shot",
            state_init_vars=state_init_vars,
            input_vars=input_vars,
            target_vars=target_vars,
        )
    else:
        dl = make_time_indep_dataloader(
            ds=ds_orig,
            time_coord="time",
            episode_coord="shot",
            input_vars=input_vars,
            target_vars=target_vars,
        )

    # Ensure time and shot coords still exist
    for coord in ["time", "shot"]:
        assert coord in dl.ds.coords, f"{coord} is missing from dataloader dataset"
    
    # Ensure the sampled data hasn't been shifted in shot or time relative to the original dataset.
    for batch in dl:
        ds_batch = batch.ds
        for sample in range(ds_batch.dims["sample"])[:1000]:  # Limit of 1000 to avoid long test time for time-independent module which has 10k+ samples
            ds_sample = ds_batch.isel(sample=sample)
            shot = ds_sample["shot"].data
            ds_shot = ds_orig.sel(shot=shot)

            # Sample times should be a subset of the original times for that shot, excepting forward-fill which we don't care about
            ds_shot_sampled = ds_shot.where(ds_shot["time"].isin(ds_sample["time"]), drop=True)
            ds_sample_real = ds_sample.where(ds_sample["time"].isin(ds_shot["time"]), drop=True)
            
            # For each variable, check the values in the dataloader sample match the values in the original dataset for the same shot and time
            for var in set(input_vars + target_vars):
                assert np.allclose(ds_sample_real[var].data, ds_shot_sampled[var].data, atol=1e-06), f"Values for variable {var} do not match between dataloader sample and original dataset for shot {shot} and overlapping times"
