import pytest
from popsim.tests.fixtures import cmod_test_dataset, reduced_cmod_test_dataset
from popsim.ml.dataloading import make_time_dep_dataloader, make_time_indep_dataloader, XarrayPreppedDataset, DEFAULT_SAMPLE_DIM
import numpy as np
from copy import deepcopy
import xarray as xr
from popsim.ml._types import TrainingMetadata

def _run_dl_checks(dl, batch_size, expected_n_samps, shuffle, segment_length, convert_xr):
    """Generic function to check the properties of a dataloader generated by make_time_dep_dataloader and make_time_indep_dataloader."""
    # "None" batch size should be equivalent to loading all samples in a single batch.
    batch_size_handle_none = batch_size if batch_size is not None else expected_n_samps

    # The number of batches should be the number of samples divided by the batch size rounded up.
    expected_n_batches = max(1, np.ceil(expected_n_samps / batch_size_handle_none).astype(int))
    assert len(dl) == expected_n_batches

    # For each batch, check it is an XarrayPreppedDataset and that the sizes are correct.
    first_batches = []
    for idx, batch in enumerate(dl):
        assert isinstance(batch, XarrayPreppedDataset)

        # Make sure the leading dimension is the sample dimension.
        assert list(batch.ds.dims.keys())[0] == DEFAULT_SAMPLE_DIM

        # Nominally, the batch size is just "batch_size_handle_none", but the last batch may be smaller.
        expected_sample_size = min(batch_size_handle_none, expected_n_samps - idx * batch_size_handle_none)

        if segment_length is not None:
            assert dict(batch.ds.sizes) == {DEFAULT_SAMPLE_DIM: expected_sample_size, 'time_slice_input': segment_length}
        else:
            assert batch.ds.sizes[DEFAULT_SAMPLE_DIM] == expected_sample_size

        inputs, targets = batch.get_inputs_and_targets()

        if convert_xr:
            assert isinstance(targets, dict)
        else:
            assert isinstance(targets, xr.Dataset)
        
        first_batches.append(deepcopy(batch))

    # Iterate through the dataloader again to check that the "shuffle" flag works as intended.
    second_round_batches = [batch for batch in dl]

    if shuffle:
        assert first_batches != second_round_batches
    else:
        assert first_batches == second_round_batches

@pytest.mark.parametrize("segmenting_case", [{"seg_length": 250, "seg_overlap": 25, "expected_n_samps" : 724}, {"seg_length": 250, "seg_overlap": 0, "expected_n_samps" : 655},
                                             {"seg_length": None, "seg_overlap": 0, "expected_n_samps" : 99}])
@pytest.mark.parametrize("batch_size", [None, 1, 64, 1024, np.iinfo(np.int32).max])
@pytest.mark.parametrize("shuffle", [True, False])
@pytest.mark.parametrize("convert_xr_to_jnp", [True, False])
def test_make_time_dep_dataloader(reduced_cmod_test_dataset, segmenting_case, batch_size, shuffle, convert_xr_to_jnp):
    ds, state_init_vars, input_vars, target_vars = reduced_cmod_test_dataset

    # expected_n_samps were determined by manually checking the dataset.
    segment_length, segment_overlap, expected_n_samps = segmenting_case["seg_length"], segmenting_case["seg_overlap"], segmenting_case["expected_n_samps"]
    dl = make_time_dep_dataloader(
        ds=ds,
        time_coord="time",
        episode_coord="shot",
        state_init_vars=state_init_vars,
        input_vars=input_vars,
        target_vars=target_vars,
        convert_xr_to_jnp=convert_xr_to_jnp,
        segment_length=segment_length,
        segment_overlap=segment_overlap,
        batch_size=batch_size,
        shuffle=shuffle
    )

    _run_dl_checks(
        dl=dl, 
        batch_size=batch_size, 
        expected_n_samps=expected_n_samps, 
        shuffle=shuffle,
        segment_length=segment_length,
        convert_xr=convert_xr_to_jnp
    )

@pytest.mark.parametrize("batch_size", [None, 1024, np.iinfo(np.int32).max])
@pytest.mark.parametrize("shuffle", [True, False])
@pytest.mark.parametrize("convert_xr_to_jnp", [True, False])
def test_make_time_indep_dataloader(reduced_cmod_test_dataset, batch_size, shuffle, convert_xr_to_jnp):
    ds, _, _, _ = reduced_cmod_test_dataset
    expected_n_samps = 151046 # Manually checked the dataset.
    dl = make_time_indep_dataloader(
        ds=ds,
        time_coord="time",
        episode_coord="shot",
        input_vars=["p_rad", "ip", "n_e"],
        target_vars=["Wmhd"],
        convert_xr_to_jnp=convert_xr_to_jnp,
        batch_size=batch_size,
        shuffle=shuffle
    )

    _run_dl_checks(
        dl=dl, 
        batch_size=batch_size, 
        expected_n_samps=expected_n_samps, 
        shuffle=shuffle,
        segment_length=None,
        convert_xr=convert_xr_to_jnp
    )

def test_prepped_ds_error(reduced_cmod_test_dataset):
    """Test that assigning the wrong sample coordinate to the TrainingMetadata raises an error."""
    ds, _, _, _ = reduced_cmod_test_dataset

    data_var_names = list(ds.data_vars.keys())

    train_meta = TrainingMetadata(
        convert_xr_to_jnp=False,
        sample_coord=data_var_names[0], # Data vars are 2D, so this should create an error.
        sample_dim="shot",
        input_vars=data_var_names[:2],
        target_vars=data_var_names[2:4],
        time_dep_metadata=TrainingMetadata.TimeDepMetadata(
            state_init_vars=data_var_names[4:],
            time_coord="time",
            time_dim="time",
        )
    )


    with pytest.raises(ValueError):
        dataset = XarrayPreppedDataset(ds, train_meta)

@pytest.mark.parametrize("batch_size", [None, 1024, np.iinfo(np.int32).max])
@pytest.mark.parametrize("time_dependent", [True, False])
@pytest.mark.parametrize("segment_length", [None, 100])
def test_dl_limit_size_cmod(reduced_cmod_test_dataset, batch_size, time_dependent, segment_length):
    """Tests for limiting dimensions in the dataloader in a typical workflow"""
    ds, state_init_vars, input_vars, target_vars = reduced_cmod_test_dataset

    convert_xr = True
    shuffle = True

    if time_dependent:
        dl = make_time_dep_dataloader(
            ds=ds,
            time_coord="time",
            episode_coord="shot",
            state_init_vars=state_init_vars,
            input_vars=input_vars,
            target_vars=target_vars,
            batch_size=batch_size,
            convert_xr_to_jnp=convert_xr,
            segment_length=segment_length,
            shuffle=shuffle
        )
    else:
        dl = make_time_indep_dataloader(
            ds=ds,
            time_coord="time",
            episode_coord="shot",
            input_vars=input_vars,
            target_vars=target_vars,
            batch_size=batch_size,
            convert_xr_to_jnp=convert_xr,
            shuffle=shuffle
        )

    # Check that we can limit by the episode coord
    lim_dl = dl.limit_size(size=10, coord="shot")
    assert np.unique(lim_dl.ds.shot).size == 10

    if time_dependent:
        # If a short segment length is provided, there should be more samples than shots
        if segment_length and (segment_length <= lim_dl.ds.sizes["time_slice_input"]):
            assert lim_dl.ds.sizes["sample"] > 10

        # Check that we can limit by the time segment dimension
        lim_dl = dl.limit_size(size=10, coord="time_slice_input")
        assert np.unique(lim_dl.ds.time_slice_input).size == 10
    else:
        # Check that we can limit by the sample dimension
        lim_dl = dl.limit_size(size=10, coord="sample")
        assert np.unique(lim_dl.ds.sample).size == 10
        _run_dl_checks(lim_dl, batch_size=batch_size, expected_n_samps=10, shuffle=shuffle, segment_length=None, convert_xr=convert_xr)

@pytest.mark.parametrize("time_dependent", [True, False])
def test_dl_limit_size_constructed(time_dependent):
    """More rigorous testing of the limit_size method, covering limit by every coordinate and dimension"""
    num_shots = 4
    num_times = 30
    ds = xr.Dataset(
        {
            "p_rad": (("shot", "time_slice"), np.random.rand(num_shots, num_times)),
            "ip": (("shot", "time_slice"), np.random.rand(num_shots, num_times)),
            "n_e": (("shot", "time_slice"), np.random.rand(num_shots, num_times)),
            "Wmhd": (("shot", "time_slice"), np.random.rand(num_shots, num_times)),
        },
        coords={
            "shot": np.arange(num_shots),
            "time_slice": np.arange(num_times),
            "time": (("shot", "time_slice"), np.tile(np.arange(num_times)*0.001, (num_shots, 1))),
        }
    )
    state_init_vars = ["Wmhd"]
    target_vars = ["p_rad"]
    input_vars = ["ip", "n_e"]

    convert_xr = True
    shuffle = False
    segment_length = 10
    batch_size = None

    if time_dependent:
        dl = make_time_dep_dataloader(
            ds=ds,
            time_coord="time",
            episode_coord="shot",
            state_init_vars=state_init_vars,
            input_vars=input_vars,
            target_vars=target_vars,
            convert_xr_to_jnp=convert_xr,
            segment_length=segment_length,
            batch_size=batch_size,
            shuffle=shuffle
        )
    else:
        dl = make_time_indep_dataloader(
            ds=ds,
            time_coord="time",
            episode_coord="shot",
            input_vars=input_vars,
            target_vars=target_vars,
            convert_xr_to_jnp=convert_xr,
            shuffle=shuffle
        )

    for coord in list(dl.ds.coords) + list(dl.ds.dims):
        lim_dl = dl.limit_size(size=2, coord=coord)
        assert np.unique(lim_dl.ds[coord]).size == 2

def test_prng(reduced_cmod_test_dataset):
    ds, _, _, _ = reduced_cmod_test_dataset
    dl = make_time_indep_dataloader(
        ds=ds,
        time_coord="time",
        episode_coord="shot",
        input_vars=["p_rad", "ip", "n_e"],
        target_vars=["Wmhd"],
        convert_xr_to_jnp=True,
        batch_size=512,
        shuffle=True,
        generate_prng=True
    )
    
    # Check that when we grab the next batch, there is a "prng_key" variable in the dataset.
    batch = next(iter(dl))
    assert "prng_key" in batch.ds
    prng_key1 = dl.ds["prng_key"].data
    
    _ = next(iter(dl))
    prng_key2 = dl.ds["prng_key"].data
    
    # Check that the prng keys are different for different batches.
    assert not np.array_equal(prng_key1, prng_key2)