import pytest
from popsim.tests.fixtures import cmod_test_dataset
from popsim.ml.dataloading import make_dataloader, make_time_indep_dataloader, XarrayPreppedDataset
import numpy as np
from copy import deepcopy

@pytest.fixture
def reduced_cmod_test_dataset(cmod_test_dataset):
    # Downsample to 100 shots for faster testing.
    ds = cmod_test_dataset
    n_shots_test = 100
    ds = ds.isel(shot=slice(0, n_shots_test))
    state_init_vars = ["Wmhd"]
    param_vars = ["ip", "n_e"]
    target_vars = ["Wmhd"]
    return ds, state_init_vars, param_vars, target_vars

def _run_dl_checks(dl, batch_size, expected_n_samps, shuffle, segment_length = None):
    """Generic function to check the properties of a dataloader generated by make_dataloader and make_time_indep_dataloader."""
    # "None" batch size should be equivalent to loading all samples in a single batch.
    batch_size_handle_none = batch_size if batch_size is not None else expected_n_samps

    # The number of batches should be the number of samples divided by the batch size rounded up.
    expected_n_batches = max(1, np.ceil(expected_n_samps / batch_size_handle_none).astype(int))
    assert len(dl) == expected_n_batches

    # For each batch, check it is an XarrayPreppedDataset and that the sizes are correct.
    first_batches = []
    for idx, batch in enumerate(dl):
        assert isinstance(batch, XarrayPreppedDataset)
        # Nominally, the batch size is just "batch_size_handle_none", but the last batch may be smaller.
        expected_sample_size = min(batch_size_handle_none, expected_n_samps - idx * batch_size_handle_none)

        if segment_length is not None:
            assert dict(batch.ds.sizes) == {'sample': expected_sample_size, 'time_slice_input': segment_length}
        else:
            assert dict(batch.ds.sizes) == {'sample': expected_sample_size}
        first_batches.append(deepcopy(batch))

    # Iterate through the dataloader again to check that the "shuffle" flag works as intended.
    second_round_batches = [batch for batch in dl]

    if shuffle:
        assert first_batches != second_round_batches
    else:
        assert first_batches == second_round_batches

@pytest.mark.parametrize("segmenting_case", [{"seg_length": 250, "seg_overlap": 25, "expected_n_samps" : 724}, {"seg_length": 250, "seg_overlap": 0, "expected_n_samps" : 655}])
@pytest.mark.parametrize("batch_size", [None, 1, 64, 1024, np.iinfo(np.int32).max])
@pytest.mark.parametrize("shuffle", [True, False])
def test_make_dataloader(reduced_cmod_test_dataset, segmenting_case, batch_size, shuffle):
    ds, state_init_vars, param_vars, target_vars = reduced_cmod_test_dataset

    # expected_n_samps were determined by manually checking the dataset.
    segment_length, segment_overlap, expected_n_samps = segmenting_case["seg_length"], segmenting_case["seg_overlap"], segmenting_case["expected_n_samps"]

    dl = make_dataloader(
        ds=ds,
        time_var="time",
        episode_var="shot",
        state_init_vars=state_init_vars,
        param_vars=param_vars,
        target_vars=target_vars,
        segment_length=segment_length,
        segment_overlap=segment_overlap,
        batch_size=batch_size,
        shuffle=shuffle
    )

    _run_dl_checks(
        dl=dl, 
        batch_size=batch_size, 
        expected_n_samps=expected_n_samps, 
        shuffle=shuffle,
        segment_length=segment_length
    )

@pytest.mark.parametrize("batch_size", [None, 1, 64, 1024, np.iinfo(np.int32).max])
@pytest.mark.parametrize("shuffle", [True, False])
def test_make_time_indep_dataloader(reduced_cmod_test_dataset, batch_size, shuffle):
    ds, _, _, _ = reduced_cmod_test_dataset
    expected_n_samps = 151046 # Manually checked the dataset.
    dl = make_time_indep_dataloader(
        ds=ds,
        time_var="time",
        episode_var="shot",
        input_vars=["p_rad", "ip", "n_e"],
        target_vars=["Wmhd"],
        batch_size=batch_size,
        shuffle=shuffle
    )

    _run_dl_checks(
        dl=dl, 
        batch_size=batch_size, 
        expected_n_samps=expected_n_samps, 
        shuffle=shuffle,
        segment_length=None
    )