name: Pytest

on:
  pull_request: null
  push:
    branches:
      - "main"

env:
  JAX_PLATFORMS: cpu

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os:
          [
            "runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }}",
            "macos-latest",
          ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Git LFS Pull
        run: git lfs pull

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Set up Python with uv
        run: uv python install ${{ matrix.python-version }}

      - name: Setup
        run: uv sync --group dev; uv run setup-radas

      - name: Tests (float64)
        # TODO enable -Werror once tests are fixed
        run: uv run pytest popsim/tests -n=auto
        timeout-minutes: 140
        env:
          JAX_ENABLE_X64: True

      - name: Core Tests (float32)
        # Run precision-sensitive core tests in float32 mode
        run: uv run pytest popsim/tests/test_*.py popsim/tests/test_ml -n=auto
        timeout-minutes: 140
        env:
          JAX_ENABLE_X64: False

      - name: CFSPOPCON jax_compatible Tests
        run: uv run pytest ./popsim/cfspopcon_jax/tests/ -n=auto
        env:
          JAX_ENABLE_X64: True

      - name: Test Notebooks
        run: uv run pytest --nbmake docs/notebooks/ -n=auto --ignore docs/notebooks/doc_ignore/ --nbmake-timeout=300 --reruns 5 --reruns-delay 1
        env:
          JAX_ENABLE_X64: True