name: Pytest

on:
  pull_request: []
  push:
    branches:
      - 'main'
  workflow_dispatch:
    tag: "Manual run"

jobs:
  radas:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.POPSIM_PAT }}

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python - --version 1.6.1

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Cache radas results
        id: radas
        uses: actions/cache@v3
        with:
          path: radas
          key: radas-${{ hashFiles('./cfspopcon/.github/workflows/make_radas_data.sh')}}

      - name: Make radas data
        if: steps.radas.outputs.cache-hit != 'true'
        run: bash ./cfspopcon/.github/workflows/make_radas_data.sh

  build:
    needs: radas
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.POPSIM_PAT }}

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python - --version 1.6.1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Setup
        run: poetry install

      - uses: actions/cache/restore@v3
        id: radas
        with:
          path: radas
          key: radas-${{ hashFiles('./cfspopcon/.github/workflows/make_radas_data.sh')}}

      - name: Check cache hit
        if: steps.radas.outputs.cache-hit != 'true'
        run: exit 1

      - name: Copy radas data
        run: cp ./radas/cases/*/output/*.nc ./cfspopcon/cfspopcon/atomic_data/

      - name: Tests
        # TODO enable -Werror once tests are fixed
        run: poetry run pytest popsim/tests

