name: Test Install Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          [
            "runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }}",
            "macos-latest",
          ]
        dev: ["n", "y"]

    env:
      INSTALL_GPU: "n"
      INSTALL_DEV: ${{ matrix.dev }}
      CI: true

    runs-on: ${{ matrix.os }}
  
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.POPSIM_PAT }}
          lfs: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Run installation
        run: |
          chmod +x install.sh
          ./install.sh

      - name: Test installation
        run: |
          poetry run python -c "import popsim; print('Popsim imported successfully')"