name: Test Install Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          [
            "runs-on,runner=8cpu-linux-x64,run-id=${{ github.run_id }}",
            "macos-latest",
          ]
        dev: ["n", "y"]

    env:
      INSTALL_GPU: "n"
      INSTALL_DEV: ${{ matrix.dev }}
      INSTALL_TEST: true
  
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run installation
        run:  bash install.sh

      - name: Test installation
        run: |
          poetry run python -c "import popsim; print('POPSIM imported successfully')"

      - name: Test radas
        run: |
          poetry run setup-radas
          if [ ! -d "atomic_data/output" ]; then
            echo "Error: Directory atomic_data/output does not exist."
            exit 1
          fi
          if [ -z "$(ls -A atomic_data/output)" ]; then
            echo "Error: Directory atomic_data/output is empty."
            exit 1
          fi
          echo "Files successfully installed in atomic_data/output."