name: Test Install Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-install:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        dev: ["n", "y"]

    env:
      INSTALL_GPU: "n"
      INSTALL_DEV: ${{ matrix.dev }}
      INSTALL_TEST: true
  
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Run installation
        run:  bash install.sh

      - name: Test installation
        run: |
          uv run python -c "import popsim; print('POPSIM imported successfully')"

      - name: Test radas
        run: |
          uv run setup-radas
          if [ ! -d "atomic_data/output" ]; then
            echo "Error: Directory atomic_data/output does not exist."
            exit 1
          fi
          if [ -z "$(ls -A atomic_data/output)" ]; then
            echo "Error: Directory atomic_data/output is empty."
            exit 1
          fi
          echo "Files successfully installed in atomic_data/output."
